server:
  port: 8080
  servlet:
    context-path: /message-app
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # MySQL连接配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/tpm_master?allowMultiQueries=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
